---
title: "RWorksheet_apuli#4a.Rmd"
author: "Marian Apuli"
date: "2025-11-24"
output: pdf_document
---

###########################################
# RWORKSHEET #4A - COMPLETE R CODE
###########################################

### 1. Shoe Size and Height Data ----

# Create data frame
shoe_size <- c(7, 8, 9, 10, 6, 7, 8)
height <- c(165, 170, 172, 180, 158, 160, 168)
gender <- c("M","F","M","M","F","F","M")

df <- data.frame(Gender = gender,
                 ShoeSize = shoe_size,
                 Height = height)

df
summary(df)

# Subsets for male and female
male_df <- subset(df, Gender == "M", select = c(ShoeSize, Height))
female_df <- subset(df, Gender == "F", select = c(ShoeSize, Height))

male_df
female_df

# Means
mean_shoe <- mean(df$ShoeSize)
mean_height <- mean(df$Height)

mean_shoe
mean_height

# Relationship (correlation)
cor(df$ShoeSize, df$Height)


### 2. Months vector to factor ----

months_vector <- c("March","April","January","November","January",
"September","October","September","November","August",
"January","November","November","February","May","August",
"July","December","August","August","September","November",
"February","April")

factor_months_vector <- factor(months_vector)

factor_months_vector


### 3. Summary comparison ----

summary(months_vector)
summary(factor_months_vector)


### 4. Factor with required order ----

factor_data <- c("East","West","North","East","West","West","North","East")

new_order_data <- factor(factor_data, levels = c("East","West","North"))
print(new_order_data)


### 5. Import CSV ----

# a. Import CSV
data_import <- read.table("import_march.csv", header = TRUE, sep = ",")

# b. View dataset
data_import
summary(data_import)


### 6. Exhaustive Search (IF-ELSE) ----

num <- as.integer(readline("Enter a number from 1 to 50: "))

if(num < 1 | num > 50){
  print("The number selected is beyond the range of 1 to 50")
} else if(num == 20){
  print(TRUE)
} else {
  print(num)
}


### 7. Minimum Bills Function ----

minBills <- function(price){
  bills <- c(1000, 500, 200, 100, 50)
  count <- 0
  remaining <- price
  
  for(b in bills){
    count <- count + remaining %/% b
    remaining <- remaining %% b
  }
  
  return(count)
}

# Example
minBills(550)


### 8. Student Math Scores ----

# a. Dataframe
Name <- c("Annie","Thea","Steve","Hanna")
Grade1 <- c(85,65,75,95)
Grade2 <- c(65,75,55,75)
Grade3 <- c(85,90,80,100)
Grade4 <- c(100,90,85,90)

df <- data.frame(Name, Grade1, Grade2, Grade3, Grade4)
df

# b. Average > 90 without rowMeans()
avg <- (df$Grade1 + df$Grade2 + df$Grade3 + df$Grade4) / 4

for(i in 1:length(avg)){
  if(avg[i] > 90){
    cat(df$Name[i], "'s average grade this semester is ", avg[i], "\n")
  }
}

# c. Tests with average < 80 (NO mean())
test_avgs <- c(
  sum(df$Grade1)/4,
  sum(df$Grade2)/4,
  sum(df$Grade3)/4,
  sum(df$Grade4)/4
)

for(i in 1:4){
  if(test_avgs[i] < 80){
    cat("The", i, "th test was difficult.\n")
  }
}

# d. Students with highest > 90 (NO max())
for(i in 1:nrow(df)){
  highest <- df[i,2]
  for(j in 3:5){
    if(df[i,j] > highest){
      highest <- df[i,j]
    }
  }
  
  if(highest > 90){
    cat(df$Name[i], "'s highest grade this semester is ", highest, "\n")
  }
}

# c. Tests with average < 80 (NO mean())
test_avgs <- c(
  sum(df$Grade1)/4,
  sum(df$Grade2)/4,
  sum(df$Grade3)/4,
  sum(df$Grade4)/4
)

for(i in 1:4){
  if(test_avgs[i] < 80){
    cat("The", i, "th test was difficult.\n")
  }
}

# d. Students with highest > 90 (NO max())
for(i in 1:nrow(df)){
  highest <- df[i,2]
  for(j in 3:5){
    if(df[i,j] > highest){
      highest <- df[i,j]
    }
  }
  
  if(highest > 90){
    cat(df$Name[i], "'s highest grade this semester is ", highest, "\n")
  }
}

